# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_recomp_rando"

# Version of this mod.
version = "0.9.4"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "MMRecompRando"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
funny zelda rando
move the zelda things around

https://github.com/RecompRando/MMRecompRando"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "NMP Edition"

# Authors of this mod.
authors = [ "LittleCube", "ThatHypedPerson", "PixelShake92", "Muervo_", "G4M3RL1F3", "dcvz", "CelestialKitsune", "VincentsSin" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    "owls_never_quit:1.0.0",
    "mm_recomp_better_double_sot:0.0.1",
    "mm_recomp_colors:0.5.0",
    "mm_no_more_patches:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# APCpp Glue:
    { name = "APCpp-Glue", funcs = ["rando_init",
                                    "rando_location_is_checked",
                                    "rando_location_is_checked_async",
                                    "rando_get_death_link_pending",
                                    "rando_reset_death_link_pending",
                                    "rando_get_death_link_enabled",
                                    "rando_send_death_link",
                                    "rando_is_magic_trap",
                                    "rando_get_camc_enabled",
                                    "rando_get_start_with_consumables_enabled",
                                    "rando_get_permanent_chateau_romani_enabled",
                                    "rando_get_start_with_inverted_time_enabled",
                                    "rando_get_receive_filled_wallets_enabled",
                                    "rando_get_remains_allow_boss_warps_enabled",
                                    "rando_get_starting_heart_locations",
                                    "rando_get_moon_remains_required",
                                    "rando_get_majora_remains_required",
                                    "rando_get_tunic_color",
                                    "rando_get_shop_price",
                                    "rando_skulltulas_enabled",
                                    "rando_shopsanity_enabled",
                                    "rando_advanced_shops_enabled",
                                    "rando_scrubs_enabled",
                                    "rando_cows_enabled",
                                    "rando_damage_multiplier",
                                    "rando_death_behavior",
                                    "rando_get_location_type",
                                    "rando_get_item_id",
                                    "rando_broadcast_location_hint",
                                    "rando_send_location",
                                    "rando_complete_goal",
                                    "rando_has_item",
                                    "rando_has_item_async",
                                    "rando_get_seed_name",
                                    "rando_get_own_slot_id",
                                    "rando_get_items_size",
                                    "rando_get_item",
                                    "rando_get_sending_player",
                                    "rando_get_item_name_from_id",
                                    "rando_get_sending_player_name",
                                    "rando_yaml_init",
                                    "rando_yaml_puts",
                                    "rando_yaml_finalize",
                                    "rando_init_solo",
                                    "rando_scan_solo_seeds",
                                    "rando_solo_count",
                                    "rando_solo_get_seed_name",
                                    "rando_solo_get_generation_date",
                                    "rando_solo_generate",
                                    "rando_get_location_item_player",
                                    "rando_get_location_item_name",
                                    "rando_get_last_location_sent"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_rando"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml", "rando_syms.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.dds" ]

[[manifest.config_options]]
id = "notification_position"
name = "Notification Position"
description = "Sets where incoming item notifications appear on your screen"
type = "Enum"
options = [ "Top Left", "Top Right", "Bottom Left", "Bottom Right" ]
default = "Top Left"
